export const food2: Record<string, string> = {
  "🍠": "sweet potato",
  "🥐": "croissant",
  "🥯": "bagel",
  "🍞": "bread",
  "🥖": "baguette",
  "🥨": "pretzel",
  "🧀": "cheese",
  "🥚": "egg",
  "🍳": "cooking fried egg",
  "🧈": "butter",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🥓": "bacon",
  "🥩": "meat steak",
  "🍗": "drumstick chicken leg",
  "🍖": "meat bone",
  "🌭": "hotdog",
  "🍔": "hamburger burger",
  "🍟": "fries french",
  "🍕": "pizza",
  "🌮": "taco",
  "🌯": "burrito",
  "🫔": "tamale",
  "🥙": "pita falafel",
  "🧆": "falafel",
  "🍲": "stew pot food",
  "🥘": "paella pan",
  "🫕": "fondue",
  "🥫": "canned food",
  "🍝": "pasta spaghetti",
};
