export const food1: Record<string, string> = {
  "🍎": "apple red fruit",
  "🍐": "pear fruit",
  "🍊": "orange tangerine fruit",
  "🍋": "lemon fruit",
  "🍌": "banana fruit",
  "🍉": "watermelon fruit",
  "🍇": "grapes fruit",
  "🍓": "strawberry fruit",
  "🫐": "blueberries fruit",
  "🍈": "melon fruit",
  "🍒": "cherries fruit",
  "🍑": "peach fruit",
  "🥭": "mango fruit",
  "🍍": "pineapple fruit",
  "🥥": "coconut",
  "🥝": "kiwi fruit",
  "🍅": "tomato",
  "🍆": "eggplant aubergine",
  "🥑": "avocado",
  "🥦": "broccoli",
  "🥬": "leafy green lettuce",
  "🥒": "cucumber",
  "🌶": "pepper hot chili",
  "🫑": "bell pepper",
  "🌽": "corn",
  "🥕": "carrot",
  "🫒": "olive",
  "🧄": "garlic",
  "🧅": "onion",
  "🥔": "potato",
};
