export const nature1: Record<string, string> = {
  "🐶": "dog puppy",
  "🐱": "cat kitty",
  "🐭": "mouse",
  "🐹": "hamster",
  "🐰": "rabbit bunny",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda",
  "🐻‍❄️": "polar bear",
  "🐨": "koala",
  "🐯": "tiger",
  "🦁": "lion",
  "🐮": "cow",
  "🐷": "pig",
  "🐸": "frog",
  "🐵": "monkey",
  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "chick baby bird",
  "🦅": "eagle",
  "🦆": "duck",
  "🦉": "owl",
  "🦇": "bat",
  "🐺": "wolf",
  "🐗": "boar",
  "🐴": "horse",
  "🦄": "unicorn",
  "🐝": "bee honey",
  "🐛": "bug caterpillar",
};
