export const objects1: Record<string, string> = {
  "📝": "memo note write",
  "📁": "folder file",
  "📂": "open folder",
  "📄": "page document",
  "📊": "chart bar graph",
  "📈": "chart up trending",
  "📉": "chart down trending",
  "💻": "laptop computer",
  "🖥": "desktop computer monitor",
  "⌨️": "keyboard",
  "🖨": "printer",
  "💾": "floppy disk save",
  "💿": "cd disc",
  "🎮": "game controller",
  "🕹": "joystick",
  "🔧": "wrench tool",
  "🔨": "hammer tool",
  "⚙️": "gear settings",
  "🔩": "nut bolt",
  "🗜": "clamp",
  "⚖️": "balance scale",
  "🔗": "link chain",
  "⛓": "chains",
  "📎": "paperclip",
  "🖇": "linked paperclips",
  "📐": "triangle ruler",
  "📏": "ruler straight",
  "📌": "pushpin pin",
  "📍": "round pushpin pin",
  "🏷": "label tag",
};
