export const objects2: Record<string, string> = {
  "🔖": "bookmark",
  "🔑": "key",
  "🗝": "old key",
  "🔒": "locked",
  "🔓": "unlocked",
  "🔔": "bell notification",
  "🔕": "bell muted",
  "📦": "package box",
  "📮": "mailbox postbox",
  "📬": "mailbox open mail",
  "📭": "mailbox empty",
  "📫": "mailbox closed",
  "🗳": "ballot box vote",
  "✏️": "pencil write",
  "✒️": "pen nib",
  "🖊": "pen",
  "🖋": "fountain pen",
  "🖌": "paintbrush art",
  "🖍": "crayon",
};
