export const people1: Record<string, string> = {
  "👋": "wave hello bye hand",
  "🤚": "raised back hand",
  "🖐": "hand splayed fingers",
  "✋": "raised hand stop high five",
  "🖖": "vulcan spock",
  "🫱": "rightward hand",
  "🫲": "leftward hand",
  "👌": "ok okay perfect",
  "🤌": "pinched fingers italian",
  "🤏": "pinching small tiny",
  "✌️": "peace victory",
  "🤞": "crossed fingers luck",
  "🫰": "hand index thumb",
  "🤟": "love you gesture",
  "🤘": "rock on horns metal",
  "🤙": "call me shaka hang loose",
  "👈": "point left",
  "👉": "point right",
  "👆": "point up",
  "🖕": "middle finger",
  "👇": "point down",
  "☝️": "index up point",
  "🫵": "point at viewer",
  "👍": "thumbs up like good yes",
  "👎": "thumbs down dislike bad no",
  "✊": "fist raised",
  "👊": "fist bump punch",
  "🤛": "left fist",
  "🤜": "right fist",
  "👏": "clap applause",
};
