export const smileys2: Record<string, string> = {
  "🤐": "zipper mouth shut",
  "🤨": "raised eyebrow skeptical",
  "😐": "neutral face",
  "😑": "expressionless blank",
  "😶": "no mouth silent",
  "🫥": "dotted line invisible",
  "😏": "smirk sly",
  "😒": "unamused",
  "🙄": "eye roll",
  "😬": "grimace awkward",
  "🤥": "lying pinocchio",
  "😌": "relieved peaceful",
  "😔": "pensive sad",
  "😪": "sleepy tired",
  "🤤": "drool",
  "😴": "sleeping zzz",
  "😷": "mask sick",
  "🤒": "thermometer sick fever",
  "🤕": "bandage hurt injured",
  "🤢": "nauseated sick green",
  "🤮": "vomit throw up",
  "🥵": "hot sweating",
  "🥶": "cold freezing",
  "🥴": "woozy dizzy drunk",
  "😵": "dizzy knocked out",
  "🤯": "mind blown exploding",
  "🤠": "cowboy hat",
  "🥳": "party celebrate birthday",
  "🥸": "disguise glasses",
  "😎": "cool sunglasses",
};
