export const smileys1: Record<string, string> = {
  "😀": "grinning happy smile",
  "😃": "smiley happy smile",
  "😄": "smile happy grin",
  "😁": "beaming grin smile",
  "😆": "laughing happy",
  "😅": "sweat smile nervous",
  "🤣": "rofl laughing rolling",
  "😂": "joy laughing tears cry",
  "🙂": "slight smile",
  "😊": "blush happy shy smile",
  "😇": "innocent angel halo",
  "🥰": "love hearts face",
  "😍": "heart eyes love",
  "🤩": "star struck excited",
  "😘": "kiss blowing",
  "😗": "kiss",
  "😚": "kiss closed eyes",
  "😙": "kiss smile",
  "🥲": "smile tear sad happy",
  "😋": "yummy delicious tongue",
  "😛": "tongue out",
  "😜": "wink tongue",
  "🤪": "zany crazy wild",
  "😝": "squint tongue",
  "🤑": "money dollar rich",
  "🤗": "hug hugging",
  "🤭": "giggle hand mouth",
  "🤫": "shush quiet secret",
  "🤔": "thinking hmm",
  "🫡": "salute",
};
