export const symbols1: Record<string, string> = {
  "❤️": "red heart love",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🤎": "brown heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "❤️‍🔥": "heart fire burning love",
  "💔": "broken heart",
  "❣️": "heart exclamation",
  "💕": "two hearts love",
  "💞": "revolving hearts",
  "💓": "heartbeat",
  "💗": "growing heart",
  "💖": "sparkling heart",
  "💘": "heart arrow cupid",
  "💝": "heart ribbon gift",
  "⭐": "star",
  "🌟": "glowing star",
  "✨": "sparkles",
  "⚡": "lightning bolt zap",
  "🔥": "fire hot flame lit",
  "💥": "boom collision",
  "☀️": "sun sunny",
  "🌈": "rainbow",
  "💯": "hundred perfect score",
  "🎯": "bullseye target",
  "♻️": "recycle",
};
