import { useState } from "react";
import {
  Box,
  Popover,
  Typography,
  IconButton,
  TextField,
  InputAdornment,
} from "@mui/material";
import SearchIcon from "@mui/icons-material/Search";
import { FONT_WEIGHT_SEMIBOLD } from "@/theme/fontWeights";

const EMOJI_CATEGORIES: Record<string, string[]> = {
  Smileys: [
    "😀",
    "😃",
    "😄",
    "😁",
    "😆",
    "😅",
    "🤣",
    "😂",
    "🙂",
    "😊",
    "😇",
    "🥰",
    "😍",
    "🤩",
    "😘",
    "😗",
    "😚",
    "😙",
    "🥲",
    "😋",
    "😛",
    "😜",
    "🤪",
    "😝",
    "🤑",
    "🤗",
    "🤭",
    "🤫",
    "🤔",
    "🫡",
    "🤐",
    "🤨",
    "😐",
    "😑",
    "😶",
    "🫥",
    "😏",
    "😒",
    "🙄",
    "😬",
    "🤥",
    "😌",
    "😔",
    "😪",
    "🤤",
    "😴",
    "😷",
    "🤒",
    "🤕",
    "🤢",
    "🤮",
    "🥵",
    "🥶",
    "🥴",
    "😵",
    "🤯",
    "🤠",
    "🥳",
    "🥸",
    "😎",
    "🤓",
    "🧐",
  ],
  People: [
    "👋",
    "🤚",
    "🖐",
    "✋",
    "🖖",
    "🫱",
    "🫲",
    "👌",
    "🤌",
    "🤏",
    "✌️",
    "🤞",
    "🫰",
    "🤟",
    "🤘",
    "🤙",
    "👈",
    "👉",
    "👆",
    "🖕",
    "👇",
    "☝️",
    "🫵",
    "👍",
    "👎",
    "✊",
    "👊",
    "🤛",
    "🤜",
    "👏",
    "🙌",
    "🫶",
    "👐",
    "🤲",
    "🤝",
    "🙏",
  ],
  Nature: [
    "🐶",
    "🐱",
    "🐭",
    "🐹",
    "🐰",
    "🦊",
    "🐻",
    "🐼",
    "🐻‍❄️",
    "🐨",
    "🐯",
    "🦁",
    "🐮",
    "🐷",
    "🐸",
    "🐵",
    "🐔",
    "🐧",
    "🐦",
    "🐤",
    "🦅",
    "🦆",
    "🦉",
    "🦇",
    "🐺",
    "🐗",
    "🐴",
    "🦄",
    "🐝",
    "🐛",
    "🦋",
    "🐌",
    "🐞",
    "🐜",
    "🪲",
    "🐢",
    "🐍",
    "🦎",
    "🐙",
    "🦑",
    "🐠",
    "🐟",
    "🐬",
    "🐳",
    "🐋",
    "🦈",
  ],
  Food: [
    "🍎",
    "🍐",
    "🍊",
    "🍋",
    "🍌",
    "🍉",
    "🍇",
    "🍓",
    "🫐",
    "🍈",
    "🍒",
    "🍑",
    "🥭",
    "🍍",
    "🥥",
    "🥝",
    "🍅",
    "🍆",
    "🥑",
    "🥦",
    "🥬",
    "🥒",
    "🌶",
    "🫑",
    "🌽",
    "🥕",
    "🫒",
    "🧄",
    "🧅",
    "🥔",
    "🍠",
    "🥐",
    "🥯",
    "🍞",
    "🥖",
    "🥨",
    "🧀",
    "🥚",
    "🍳",
    "🧈",
    "🥞",
    "🧇",
    "🥓",
    "🥩",
    "🍗",
    "🍖",
    "🌭",
    "🍔",
    "🍟",
    "🍕",
    "🌮",
    "🌯",
    "🫔",
    "🥙",
    "🧆",
    "🥚",
    "🍲",
    "🥘",
    "🫕",
    "🥫",
    "🍝",
    "🍜",
    "🍛",
  ],
  Objects: [
    "📝",
    "📁",
    "📂",
    "📄",
    "📊",
    "📈",
    "📉",
    "💻",
    "🖥",
    "⌨️",
    "🖨",
    "💾",
    "💿",
    "🎮",
    "🕹",
    "🔧",
    "🔨",
    "⚙️",
    "🔩",
    "🗜",
    "⚖️",
    "🔗",
    "⛓",
    "📎",
    "🖇",
    "📐",
    "📏",
    "📌",
    "📍",
    "🏷",
    "🔖",
    "🔑",
    "🗝",
    "🔒",
    "🔓",
    "🔔",
    "🔕",
    "📦",
    "📮",
    "📬",
    "📭",
    "📫",
    "🗳",
    "✏️",
    "✒️",
    "🖊",
    "🖋",
    "🖌",
    "🖍",
    "📎",
    "📐",
    "📏",
  ],
  Symbols: [
    "❤️",
    "🧡",
    "💛",
    "💚",
    "💙",
    "💜",
    "🤎",
    "🖤",
    "🤍",
    "❤️‍🔥",
    "💔",
    "❣️",
    "💕",
    "💞",
    "💓",
    "💗",
    "💖",
    "💘",
    "💝",
    "⭐",
    "🌟",
    "✨",
    "⚡",
    "🔥",
    "💥",
    "☀️",
    "🌈",
    "💯",
    "🎯",
    "♻️",
    "✅",
    "❌",
    "❓",
    "❗",
    "⚠️",
    "🚫",
    "🔴",
    "🟠",
    "🟡",
    "🟢",
    "🔵",
    "🟣",
    "🟤",
    "⚫",
    "⚪",
  ],
};

/** Maps emojis to searchable keywords for per-emoji filtering */
const EMOJI_KEYWORDS: Record<string, string> = {
  // Smileys
  "😀": "grinning happy smile",
  "😃": "smiley happy smile",
  "😄": "smile happy grin",
  "😁": "beaming grin smile",
  "😆": "laughing happy",
  "😅": "sweat smile nervous",
  "🤣": "rofl laughing rolling",
  "😂": "joy laughing tears cry",
  "🙂": "slight smile",
  "😊": "blush happy shy smile",
  "😇": "innocent angel halo",
  "🥰": "love hearts face",
  "😍": "heart eyes love",
  "🤩": "star struck excited",
  "😘": "kiss blowing",
  "😗": "kiss",
  "😚": "kiss closed eyes",
  "😙": "kiss smile",
  "🥲": "smile tear sad happy",
  "😋": "yummy delicious tongue",
  "😛": "tongue out",
  "😜": "wink tongue",
  "🤪": "zany crazy wild",
  "😝": "squint tongue",
  "🤑": "money dollar rich",
  "🤗": "hug hugging",
  "🤭": "giggle hand mouth",
  "🤫": "shush quiet secret",
  "🤔": "thinking hmm",
  "🫡": "salute",
  "🤐": "zipper mouth shut",
  "🤨": "raised eyebrow skeptical",
  "😐": "neutral face",
  "😑": "expressionless blank",
  "😶": "no mouth silent",
  "🫥": "dotted line invisible",
  "😏": "smirk sly",
  "😒": "unamused",
  "🙄": "eye roll",
  "😬": "grimace awkward",
  "🤥": "lying pinocchio",
  "😌": "relieved peaceful",
  "😔": "pensive sad",
  "😪": "sleepy tired",
  "🤤": "drool",
  "😴": "sleeping zzz",
  "😷": "mask sick",
  "🤒": "thermometer sick fever",
  "🤕": "bandage hurt injured",
  "🤢": "nauseated sick green",
  "🤮": "vomit throw up",
  "🥵": "hot sweating",
  "🥶": "cold freezing",
  "🥴": "woozy dizzy drunk",
  "😵": "dizzy knocked out",
  "🤯": "mind blown exploding",
  "🤠": "cowboy hat",
  "🥳": "party celebrate birthday",
  "🥸": "disguise glasses",
  "😎": "cool sunglasses",
  "🤓": "nerd glasses",
  "🧐": "monocle curious",
  // People
  "👋": "wave hello bye hand",
  "🤚": "raised back hand",
  "🖐": "hand splayed fingers",
  "✋": "raised hand stop high five",
  "🖖": "vulcan spock",
  "🫱": "rightward hand",
  "🫲": "leftward hand",
  "👌": "ok okay perfect",
  "🤌": "pinched fingers italian",
  "🤏": "pinching small tiny",
  "✌️": "peace victory",
  "🤞": "crossed fingers luck",
  "🫰": "hand index thumb",
  "🤟": "love you gesture",
  "🤘": "rock on horns metal",
  "🤙": "call me shaka hang loose",
  "👈": "point left",
  "👉": "point right",
  "👆": "point up",
  "🖕": "middle finger",
  "👇": "point down",
  "☝️": "index up point",
  "🫵": "point at viewer",
  "👍": "thumbs up like good yes",
  "👎": "thumbs down dislike bad no",
  "✊": "fist raised",
  "👊": "fist bump punch",
  "🤛": "left fist",
  "🤜": "right fist",
  "👏": "clap applause",
  "🙌": "raised hands celebration",
  "🫶": "heart hands love",
  "👐": "open hands",
  "🤲": "palms up together",
  "🤝": "handshake deal",
  "🙏": "pray please thanks folded hands",
  // Nature
  "🐶": "dog puppy",
  "🐱": "cat kitty",
  "🐭": "mouse",
  "🐹": "hamster",
  "🐰": "rabbit bunny",
  "🦊": "fox",
  "🐻": "bear",
  "🐼": "panda",
  "🐻‍❄️": "polar bear",
  "🐨": "koala",
  "🐯": "tiger",
  "🦁": "lion",
  "🐮": "cow",
  "🐷": "pig",
  "🐸": "frog",
  "🐵": "monkey",
  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "chick baby bird",
  "🦅": "eagle",
  "🦆": "duck",
  "🦉": "owl",
  "🦇": "bat",
  "🐺": "wolf",
  "🐗": "boar",
  "🐴": "horse",
  "🦄": "unicorn",
  "🐝": "bee honey",
  "🐛": "bug caterpillar",
  "🦋": "butterfly",
  "🐌": "snail",
  "🐞": "ladybug",
  "🐜": "ant",
  "🪲": "beetle",
  "🐢": "turtle tortoise",
  "🐍": "snake",
  "🦎": "lizard",
  "🐙": "octopus",
  "🦑": "squid",
  "🐠": "fish tropical",
  "🐟": "fish",
  "🐬": "dolphin",
  "🐳": "whale spouting",
  "🐋": "whale",
  "🦈": "shark",
  // Food
  "🍎": "apple red fruit",
  "🍐": "pear fruit",
  "🍊": "orange tangerine fruit",
  "🍋": "lemon fruit",
  "🍌": "banana fruit",
  "🍉": "watermelon fruit",
  "🍇": "grapes fruit",
  "🍓": "strawberry fruit",
  "🫐": "blueberries fruit",
  "🍈": "melon fruit",
  "🍒": "cherries fruit",
  "🍑": "peach fruit",
  "🥭": "mango fruit",
  "🍍": "pineapple fruit",
  "🥥": "coconut",
  "🥝": "kiwi fruit",
  "🍅": "tomato",
  "🍆": "eggplant aubergine",
  "🥑": "avocado",
  "🥦": "broccoli",
  "🥬": "leafy green lettuce",
  "🥒": "cucumber",
  "🌶": "pepper hot chili",
  "🫑": "bell pepper",
  "🌽": "corn",
  "🥕": "carrot",
  "🫒": "olive",
  "🧄": "garlic",
  "🧅": "onion",
  "🥔": "potato",
  "🍠": "sweet potato",
  "🥐": "croissant",
  "🥯": "bagel",
  "🍞": "bread",
  "🥖": "baguette",
  "🥨": "pretzel",
  "🧀": "cheese",
  "🥚": "egg",
  "🍳": "cooking fried egg",
  "🧈": "butter",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🥓": "bacon",
  "🥩": "meat steak",
  "🍗": "drumstick chicken leg",
  "🍖": "meat bone",
  "🌭": "hotdog",
  "🍔": "hamburger burger",
  "🍟": "fries french",
  "🍕": "pizza",
  "🌮": "taco",
  "🌯": "burrito",
  "🫔": "tamale",
  "🥙": "pita falafel",
  "🧆": "falafel",
  "🍲": "stew pot food",
  "🥘": "paella pan",
  "🫕": "fondue",
  "🥫": "canned food",
  "🍝": "pasta spaghetti",
  "🍜": "noodles ramen",
  "🍛": "curry rice",
  // Objects
  "📝": "memo note write",
  "📁": "folder file",
  "📂": "open folder",
  "📄": "page document",
  "📊": "chart bar graph",
  "📈": "chart up trending",
  "📉": "chart down trending",
  "💻": "laptop computer",
  "🖥": "desktop computer monitor",
  "⌨️": "keyboard",
  "🖨": "printer",
  "💾": "floppy disk save",
  "💿": "cd disc",
  "🎮": "game controller",
  "🕹": "joystick",
  "🔧": "wrench tool",
  "🔨": "hammer tool",
  "⚙️": "gear settings",
  "🔩": "nut bolt",
  "🗜": "clamp",
  "⚖️": "balance scale",
  "🔗": "link chain",
  "⛓": "chains",
  "📎": "paperclip",
  "🖇": "linked paperclips",
  "📐": "triangle ruler",
  "📏": "ruler straight",
  "📌": "pushpin pin",
  "📍": "round pushpin pin",
  "🏷": "label tag",
  "🔖": "bookmark",
  "🔑": "key",
  "🗝": "old key",
  "🔒": "locked",
  "🔓": "unlocked",
  "🔔": "bell notification",
  "🔕": "bell muted",
  "📦": "package box",
  "📮": "mailbox postbox",
  "📬": "mailbox open mail",
  "📭": "mailbox empty",
  "📫": "mailbox closed",
  "🗳": "ballot box vote",
  "✏️": "pencil write",
  "✒️": "pen nib",
  "🖊": "pen",
  "🖋": "fountain pen",
  "🖌": "paintbrush art",
  "🖍": "crayon",
  // Symbols
  "❤️": "red heart love",
  "🧡": "orange heart",
  "💛": "yellow heart",
  "💚": "green heart",
  "💙": "blue heart",
  "💜": "purple heart",
  "🤎": "brown heart",
  "🖤": "black heart",
  "🤍": "white heart",
  "❤️‍🔥": "heart fire burning love",
  "💔": "broken heart",
  "❣️": "heart exclamation",
  "💕": "two hearts love",
  "💞": "revolving hearts",
  "💓": "heartbeat",
  "💗": "growing heart",
  "💖": "sparkling heart",
  "💘": "heart arrow cupid",
  "💝": "heart ribbon gift",
  "⭐": "star",
  "🌟": "glowing star",
  "✨": "sparkles",
  "⚡": "lightning bolt zap",
  "🔥": "fire hot flame lit",
  "💥": "boom collision",
  "☀️": "sun sunny",
  "🌈": "rainbow",
  "💯": "hundred perfect score",
  "🎯": "bullseye target",
  "♻️": "recycle",
  "✅": "check mark done yes",
  "❌": "cross mark no wrong",
  "❓": "question",
  "❗": "exclamation important",
  "⚠️": "warning caution",
  "🚫": "prohibited forbidden",
  "🔴": "red circle",
  "🟠": "orange circle",
  "🟡": "yellow circle",
  "🟢": "green circle",
  "🔵": "blue circle",
  "🟣": "purple circle",
  "🟤": "brown circle",
  "⚫": "black circle",
  "⚪": "white circle",
};

interface EmojiPickerProps {
  anchorEl: HTMLElement | null;
  onClose: () => void;
  onSelect: (emoji: string) => void;
}

export default function EmojiPicker({
  anchorEl,
  onClose,
  onSelect,
}: EmojiPickerProps) {
  const [search, setSearch] = useState("");

  const displayEmojis = search
    ? Object.values(EMOJI_CATEGORIES)
        .flat()
        .filter((emoji) => {
          const keywords = EMOJI_KEYWORDS[emoji];
          return keywords?.toLowerCase().includes(search.toLowerCase());
        })
        .slice(0, 80)
    : null;

  const handleSelect = (emoji: string) => {
    onSelect(emoji);
    onClose();
    setSearch("");
  };

  return (
    <Popover
      open={Boolean(anchorEl)}
      anchorEl={anchorEl}
      onClose={() => {
        onClose();
        setSearch("");
      }}
      anchorOrigin={{ vertical: "bottom", horizontal: "left" }}
    >
      <Box sx={{ width: 320, maxHeight: 360, p: 1.5 }}>
        <TextField
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search emojis..."
          size="small"
          slotProps={{
            input: {
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon fontSize="small" color="action" />
                </InputAdornment>
              ),
            },
          }}
        />
        <Box sx={{ mt: 1, maxHeight: 280, overflowY: "auto" }}>
          {/* Remove icon option */}
          <IconButton
            size="small"
            aria-label="Remove icon"
            onClick={() => {
              onSelect("");
              onClose();
            }}
            sx={{
              fontSize: "11px",
              color: "text.secondary",
              borderRadius: 1,
              mb: 1,
            }}
          >
            Remove icon
          </IconButton>

          {displayEmojis ? (
            <Box sx={{ display: "flex", flexWrap: "wrap" }}>
              {displayEmojis.map((emoji, i) => (
                <IconButton
                  key={i}
                  size="small"
                  onClick={() => handleSelect(emoji)}
                  sx={{ fontSize: "20px", width: 36, height: 36 }}
                >
                  {emoji}
                </IconButton>
              ))}
            </Box>
          ) : (
            Object.entries(EMOJI_CATEGORIES).map(([category, emojis]) => (
              <Box key={category} sx={{ mb: 1 }}>
                <Typography
                  variant="caption"
                  sx={{
                    color: "text.secondary",
                    fontWeight: FONT_WEIGHT_SEMIBOLD,
                    fontSize: "11px",
                    px: 0.5,
                  }}
                >
                  {category}
                </Typography>
                <Box sx={{ display: "flex", flexWrap: "wrap" }}>
                  {emojis.map((emoji, i) => (
                    <IconButton
                      key={i}
                      size="small"
                      onClick={() => handleSelect(emoji)}
                      sx={{ fontSize: "20px", width: 36, height: 36 }}
                    >
                      {emoji}
                    </IconButton>
                  ))}
                </Box>
              </Box>
            ))
          )}
        </Box>
      </Box>
    </Popover>
  );
}
