/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WRouteImport } from './routes/w'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WIndexRouteImport } from './routes/w/index'
import { Route as SharedIndexRouteImport } from './routes/shared/index'
import { Route as WPageIdRouteImport } from './routes/w/$pageId'
import { Route as SharedPageIdRouteImport } from './routes/shared.$pageId'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'

const WRoute = WRouteImport.update({
  id: '/w',
  path: '/w',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIndexRoute = WIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WRoute,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRoute,
} as any)
const WPageIdRoute = WPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => WRoute,
} as any)
const SharedPageIdRoute = SharedPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => SharedRoute,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shared': typeof SharedRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/shared/$pageId': typeof SharedPageIdRoute
  '/w/$pageId': typeof WPageIdRoute
  '/shared/': typeof SharedIndexRoute
  '/w/': typeof WIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/shared/$pageId': typeof SharedPageIdRoute
  '/w/$pageId': typeof WPageIdRoute
  '/shared': typeof SharedIndexRoute
  '/w': typeof WIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/shared': typeof SharedRouteWithChildren
  '/w': typeof WRouteWithChildren
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/shared/$pageId': typeof SharedPageIdRoute
  '/w/$pageId': typeof WPageIdRoute
  '/shared/': typeof SharedIndexRoute
  '/w/': typeof WIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/shared'
    | '/w'
    | '/share/$shareToken'
    | '/shared/$pageId'
    | '/w/$pageId'
    | '/shared/'
    | '/w/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/share/$shareToken'
    | '/shared/$pageId'
    | '/w/$pageId'
    | '/shared'
    | '/w'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/shared'
    | '/w'
    | '/share/$shareToken'
    | '/shared/$pageId'
    | '/w/$pageId'
    | '/shared/'
    | '/w/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SharedRoute: typeof SharedRouteWithChildren
  WRoute: typeof WRouteWithChildren
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/': {
      id: '/w/'
      path: '/'
      fullPath: '/w/'
      preLoaderRoute: typeof WIndexRouteImport
      parentRoute: typeof WRoute
    }
    '/shared/': {
      id: '/shared/'
      path: '/'
      fullPath: '/shared/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof SharedRoute
    }
    '/w/$pageId': {
      id: '/w/$pageId'
      path: '/$pageId'
      fullPath: '/w/$pageId'
      preLoaderRoute: typeof WPageIdRouteImport
      parentRoute: typeof WRoute
    }
    '/shared/$pageId': {
      id: '/shared/$pageId'
      path: '/$pageId'
      fullPath: '/shared/$pageId'
      preLoaderRoute: typeof SharedPageIdRouteImport
      parentRoute: typeof SharedRoute
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SharedRouteChildren {
  SharedPageIdRoute: typeof SharedPageIdRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

const SharedRouteChildren: SharedRouteChildren = {
  SharedPageIdRoute: SharedPageIdRoute,
  SharedIndexRoute: SharedIndexRoute,
}

const SharedRouteWithChildren =
  SharedRoute._addFileChildren(SharedRouteChildren)

interface WRouteChildren {
  WPageIdRoute: typeof WPageIdRoute
  WIndexRoute: typeof WIndexRoute
}

const WRouteChildren: WRouteChildren = {
  WPageIdRoute: WPageIdRoute,
  WIndexRoute: WIndexRoute,
}

const WRouteWithChildren = WRoute._addFileChildren(WRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SharedRoute: SharedRouteWithChildren,
  WRoute: WRouteWithChildren,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
